101-Coconsulting/TC3005B.501-Backend

.env.example, controllers/README.md, database/README.md, index.js, middleware/README.md, package-lock.json, package.json, pnpm-lock.yaml, routes/README.md
Added README files with general info to the directories. This should be enough to begin developing in a more modular way and avoid conflicts.
Still not sure how the database directory should be done for the schema and data files. Must check with @101-Coconsulting/db.
The index.js file is very basic and has the starting node project modules.
=> chore(file structure) Added directories for controllers, database, middleware and routes.

database/Documentation/SQL_Contribuiting.md
Just commiting the SQL_Contribuiting in a new folder (Documentation) inside the DataBase folder /database/Documentation/SQL_Contribuiting.md
=> Commiting SQL_Contribuiting

CONTRIBUTING.md
Created markdown file for contributing for node
=> chore: created contributing file for node

database/config/db.js, database/config/db_example.js, package-lock.json, package.json
This PR includes the connection to the DB as well as an example file to test the connection to the DB.
1. Having an existing DB
2. Having an account with permissions to connect to the DB (can be root)
1. Download the necessary dependencias using your preferred package manager:
For NPM: `npm i `
3. Ensure that the DB variables are correct inside your `.env`
4. Check if the current query is relevant to the DB being tested. Otherwise, feel free to replace it with any other query of your choice.
5. Inside `database/config ` run the command `node db_example.js`
=> 56 task db connection

database/config/db.js
I wrote an incorrect path and fixed it :(
=> 59 task fix db connection

database/Schema/Scheme.sql
Request table created, it will be edited in the future to add the foreign keys!!
=> Feature(DB) Request_Table created

.env.example, database/Schema/Scheme.sql, database/config/init_db.js, database/config/test_db.js, pnpm-lock.yaml
_What version will this next one be?_
_Outline what this new version will introduce and the changes it will make._
_List the related User Stories, Sub-Epics, and Epics that the Release advances or deals with._
=> 73 sub task creating mariadb scheme

database/MOCK_DB_SETUP.md
This PR includes a `.md` file that should be used as a guide to set up a mock DB using the MariaDB CLI to test API endpoints **temporarily** until the final DB is completed.
All endpoints created before the final DB is included in the project should be tested using the mock DB that each developer will configure individually according to their necessities.
N/A
=> docs: Created guide to configure a mock db using MariaDB CLI

database/Schema/Scheme.sql
Implements the Country table following SQL standards, creating a simple structure to store country information with unique identifiers.
[Task]: Creating all scheme tables #35
[Task]: Creating all scheme tables #35
=> 44 sub task create country table

database/Schema/Scheme.sql
_What version will this next one be?_
_Outline what this new version will introduce and the changes it will make._
_List the related User Stories, Sub-Epics, and Epics that the Release advances or deals with._
=> Tipo feature(db): finished Receipt table, closes issue #45

database/Schema/Scheme.sql
A table named Route_Request was created to establish a relationship between route requests, requests, and routes. It includes three columns: route_request_id, which serves as the identifier for each route request entry; request_id, which links the route request to a specific request; and route_id, which connects it to a specific route. All columns are of integer type.
=>  finished route_request table, closes issue #41

database/Schema/Scheme.sql
A table named City was created to store information about cities. It includes two columns: city_id, an integer that serves as the primary key to uniquely identify each city, and city_name, a variable character field with a maximum length of 100 characters to store the name of the city.
=> 43 sub task create city tabl

database/Schema/Scheme.sql
_What version will this next one be?_
_Outline what this new version will introduce and the changes it will make._
_List the related User Stories, Sub-Epics, and Epics that the Release advances or deals with._
=> feature(db): finished Department table

database/Schema/Scheme.sql
_What version will this next one be?_
_Outline what this new version will introduce and the changes it will make._
_List the related User Stories, Sub-Epics, and Epics that the Release advances or deals with._
=> feature(db): finished Receipt_Type table

database/Schema/Dummy.sql, database/Schema/Prepopulate.sql, database/Schema/Scheme.sql
Standardized schema, added prepopulation file for Receipt_Type, Roles and Request_status tables.
=> 97 task information manual insert

database/Schema/Scheme.sql
Created a field for creation_date in request table
#19 #21 #22
=> feat(db): added creation_date in request table

database/Schema/Dummy.sql
This PR will be merge to branch #99  Create dummy data for DB. This PR only includes 10 examples of Dummy data for "City" table
Once all Scheme Tables are full of dummy data, backend team will be able to make tests for their endpoints.
In branch #99 will be some some merge conflicts that will be resolved before we merge into development branch.
=> Added 10 examples of dummy data for City Table

database/Schema/Dummy.sql
This PR will be merge to branch #99  Create dummy data for DB. This PR only includes 10 examples of Dummy data for "Country" table
Once all Scheme Tables are full of dummy data, backend team will be able to make tests for their endpoints.
In branch #99 will be some some merge conflicts that will be resolved before we merge into development branch.
=> 104 sub task create dummy data for table country

database/Schema/Views.sql
created UserRequestHistory view
#18 
#103 #104 #105 #107 #115
=> feat(db): created UserRequestHistory view

database/Schema/Dummy.sql
- [X ] This is a required activity that does not directly relate to any User Stories.
- [X ] PR is linked to a standalone `chore` Task Issue: Create Dummy data for DB
Dummy Data for DB 
Create Dummy data for DB 
Create Dummy data for DB
=> feature(db): finished dummy data for Request table

database/Schema/Dummy.sql
- [X ] This is a required activity that does not directly relate to any User Stories.
- [X ] PR is linked to a standalone `chore` Task Issue: Create Dummy data for DB
Dummy Data for DB 
Create Dummy data for DB 
Create Dummy data for DB
=> feature(db): finished dummy data for Route_Request table

database/Schema/Dummy.sql
Dummy data added to the Receipt table for backend testing.
102 sub task create dummy data for table alert #121 
[Sub-Task]: [Task]: Create dummy data for DB #99
=> 108 sub task create dummy data for table receipt

database/Schema/Dummy.sql
Dummy data added to the Alert table for backend testing.
[Sub-Task]: Create dummy data for table Receipt #108
[Task]: Create dummy data for DB #99
=> 102 sub task create dummy data for table alert

.gitignore, controllers/travelAgentController.js, index.js, models/travelAgentModel.js, routes/travelAgentRoutes.js
This pr has the necessary changes for the endpoint used by Travel Agency users to change the status of a request to 4 (might be changed to 5 after reviewing the approval flow.) It also has a query in `travelAgentModel.js` to verify if the request which status is being changed exists in the database, although this has not yet been tested.
N/A
N/A
=> endpoint: api/attend-travel-request/:id

controllers/applicantController.js, database/Schema/Scheme.sql, models/applicantModel.js, routes/applicantRoutes.js, services/applicantService.js, services/countries.json
This feature introduces the **Travel Request creation endpoint** to the backend API. The endpoint allows users to create a travel request by submitting trip details, including:
- **Origin country and city**.
- **Destination country and city**.
- **Travel dates** (beginning and ending).
- **Requested and imposed fee**.
- **Additional routes** for multi-leg trips.
Once merged, this will allow users to create travel requests through the API and integrate with the backend systems for trip management and approval.
- _N/A_ (If any issues are blocked by this feature, list them here).
- _N/A_ (If any issues will be affected or require merging from `development` after this PR is merged, list them here).
=> 13 sub task create endpoint create travel request

controllers/applicantController.js, models/applicantModel.js, routes/applicantRoutes.js
This Pull Request introduces a new endpoint `GET /api/applicants/get-cc/:user_id` that allows retrieving the department information—including the cost center—associated with a specific user based on their `user_id`.
What was added:
- A method in the `Applicant` model to perform a `JOIN` between the `User` and `Department` tables.
- A new controller method `getCostCenterByUserId` in `applicantController.js`.
- A new route in `applicantRoutes.js` to expose this endpoint.
This enhancement enables the frontend and API clients (e.g., Postman) to fetch the cost center directly and accurately, which is essential for travel request creation workflows.
- Once this PR is merged, the feature for creating travel requests can leverage this endpoint to pre-fill or validate the associated cost center.
- …
=> 14 sub task create endpoint get ccuser

controllers/applicantController.js, models/applicantModel.js, routes/applicantRoutes.js
API endpoint to obtain a traveler's completed requests 
NA
NA
=> 18 sub task create endpoint get completed requestsuser

controllers/applicantController.js, database/Schema/Views.sql, models/applicantModel.js, routes/applicantRoutes.js, services/applicantService.js
This PR implements the **`/create-expense-validation`** bulk-insert endpoint that allows the frontend to submit multiple receipts in a single request.  
- **Model**: added `createExpenseBatch()` to perform a single `INSERT INTO Receipt (…) VALUES …` statement.  
- **Service**: added `createExpenseValidationBatch()` to validate input and call the model.  
- **Controller**: added `createExpenseValidationHandler()` to parse `req.body.receipts`, handle errors, and return `201 Created` with the count of inserted rows.  
- **Routes**: mounted `POST /create-expense-validation` under the `/api/applicants` router.
_None._
Issues that use the applicant files, such as #12 and its subissues must merge from dev to avoid conflicts @RicardoCalvoP\
=> 16 task applicant expenses

controllers/authorizerController.js, index.js, models/authorizerModel.js, routes/authorizerRoutes.js
- [x ] PR is linked to an issue: #26 
- [ x] PR is from feature branch created from the `#29 sub task` branch.
- [ x] `git` conventional commits.
=> 29 sub task

database/Schema/Triggers.sql
Created a trigger that automatically deletes an alert if it is related with a request that has a request status of finished, canceled or rejected.
N/A
#23
=> 166-task-create-a-trigger-that-automatically-deletes-an-alert

database/Schema/Triggers.sql
trigger to deactivate a request
N/A
#29
=> 165-task-create-a-trigger-to-deactivate-a-request

controllers/applicantController.js, models/applicantModel.js
This PR fixes the format that the endpoint returns so that it matches exactly thw standard defined in the `.yaml`
N/A
N/A
N/A
=> 20 sub task create endpoint get completed requestsuser

controllers/authorizerController.js, index.js, models/authorizerModel.js, routes/authorizerRoutes.js, services/authorizerService.js
- [ x] PR is linked to an issue: #26 
- [ x] PR is from feature branch created from the `#28 sub task` branch.
- [x ] `git` conventional commits.
=> feat: created endpoint /authorize-travel-request

database/Schema/Dummy.sql, database/Schema/Scheme.sql
Fixed dummy data in receipt table. Changed enum values in Scheme.sql for consistency sake with the dummy data.
Any issues related with receipt table
Any issues related with receipt table
=> 179 task fix database dummy data for receipt

database/Schema/Views.sql
This PR creates a view for the full user info. This includes the following fields: user_id, user_name, email, role_name and department_name.
Issue: [Sub-Task]: Create View to get a users full information #154
=> feat(db): add view for full user info

database/Schema/Dummy.sql, database/Schema/Scheme.sql
Changed Alert table. Changed alert table dummy data.
#23 
n/a
=> 182 sub task change alert table to include request

database/Schema/Dummy.sql, database/Schema/Scheme.sql
set characters to be utf8 inside the creation of the database
n/a
n/a
=> 192-task-standardize-characters-in-database

database/Schema/Dummy.sql
Dummy.sql file has been modified to add 30 more examples of dummy data to the 'Receipt' table; this will help to Endpoint's tests having more variety in the dummy data.
#196
#18 
#197
#198 
#199 
#200 
#201 
#203 
#204 
#205
=> Added 30 dummy data examples for 'Receipt' table.sql

controllers/applicantController.js, models/applicantModel.js, routes/applicantRoutes.js, services/applicantService.js
This Pull Request adds the ability for applicants to cancel their travel requests through the `/cancel-travel-request/{request_id}` endpoint.  
The cancellation is only permitted if the request is in status 1 to 5. Upon cancellation, the request's `request_status_id` is updated to `9` (Cancelado), and the `active` field is set to `false`.  
_None_
_None_
=> feat: created endpoint to cancel a request

controllers/authorizerController.js, database/Schema/Dummy.sql, database/Schema/Scheme.sql, models/authorizerModel.js, routes/authorizerRoutes.js
Created endpoint /get-alerts
#20 
n/a
=> feat(db): added endpoint /get-alerts

database/Schema/Dummy.sql
added 30 new department records to the Department table, bringing the total to 40 departments.
=> Added 30 dummy data examples for 'department' table.sql

README.md
Include a _Getting Started_ section in the `README.md` file which includes all necessary instructions required to run the current version of the Backend. Either for external users, for testers, or developers, having these steps laid out for reference would be helpful for anyone requiring to run it.
Not an issue per say, but PR #223 should wait for this to be included before it is merged. And suggestions made on 101-Coconsulting/TC3005B.501-Frontend#77 should also be considered as possible additions in the future. For uniformity of the project as a whole.
_N/A_
=> 221 task getting started instructions

database/Schema/Dummy.sql, database/Schema/Prepopulate.sql, database/Schema/Scheme.sql, database/Schema/Triggers.sql
Created AlertMessages table with data to prepopulate. Modified Alert table to include these messages. Created trigger to automatically inert a new alert when a new request is created. Created a trigger to manage an existing alert once a row is updated in Request table.
n/a
#196 #20 #23 #190
=> 212 task alert creation

models/applicantModel.js
Renamed the table used in the `get-cc` endpoint to start with an uppercase letter in accordance with the naming standard and to resolve a runtime error. This change ensures consistency across the codebase and prevents case-sensitivity issues during execution.
N/A
#14
=> fix: changed table name to start with mayus on get-cc endpoint

controllers/authorizerController.js, models/authorizerModel.js, routes/authorizerRoutes.js, services/authorizerService.js
Changed parameter names to match .yaml contents
=> 243 sub task fixing endpoint authorize travel request

controllers/accountsPayableController.js, models/accountsPayableModel.js, routes/accountsPayableRoutes.js
Changed parameter names to match .yaml contents in Travel Agent & Accounts Payable
=> 249 sub task fixing endpoint attend travel requestid

controllers/applicantController.js, models/applicantModel.js
=> fix: Corrected date format in creation_date and returned origin and destination country

controllers/authorizerController.js, models/authorizerModel.js, routes/authorizerRoutes.js
Changed parameter names to match .yaml contents
=> 244 sub task fixing endpoint decline travel request

controllers/accountsPayableController.js, models/accountsPayableModel.js
I had previously added an incorrect validation to one of the endpoints (attend-travel-request on behalf of accounts payable) and removed it in this PR.
Issue with attend-travel-request
This PR should be merged before the Release 0.2
=> fix: endpoint attend-travel-request cpp

index.js, package-lock.json, package.json
Added CORS to have HTTP request on the same origin
None
None
=> chore: added cors config to index.js

controllers/accountsPayableController.js, models/accountsPayableModel.js, routes/accountsPayableRoutes.js
feat(api): implement getExpenseValidations with optional status filter and formatted response
- Added SQL query to fetch receipts joined with receipt_type
- Supported conditional filtering by status ('todos' includes all)
- Transformed the raw results into a structured format:
{
request_id: <number>,
Expenses: [
{
receipt_id,
receipt_type_name,
amount,
Expense_Status
}
]
}
Endpoint used: 'https://localhost:3000/api/accounts-payable/get-expense-validations/1/Todos'
Need to make sure to have amount dummy data in Receipt table when using!!
=> 171 sub task create endpoint get expense validationsdeptstatusn

controllers/applicantController.js, index.js, models/applicantModel.js, package.json, routes/applicantRoutes.js, services/applicantService.js
Creates a draft of travel request when clicked save, this only starts up the travel request giving the request an 'open' status.
#274
=> 273 sub task create endpoint save draft travel requestuser

database/Schema/Views.sql, models/adminModel.js
This PR includes changes made to the /admin/get-user-endpoint in order to show only users that are active.
> [!NOTE]
Update your views before testing the endpoint! It is not necessary to re-run all DB files, only `Views.sql`
N/A
N/A
=> 296 task refactor get users list to show only active users

database/Schema/Triggers.sql
_"When a Receipt is Rejected it changes to status "Rejected", and the Request status is changed to "Comprobación de gastos" it should go back to "Pending"_
If there's a rejected receipt, this trigger changes the status to rejected, and the request status goes back to pending
N/A
#109
=> 302 task trigger to change receipt to pending when rejected

database/QuickSetup.sql
This file.sql have been created to make faster the DB setup to expedite tests. The function of this file will turn obsolete when #259 is finished.
NA
NA
=> QuickSetup file created

index.js
=> chore: COCO API signature

database/Schema/Scheme.sql
Created a new table for logging requests
#318 #319 
n/a
=> feat(db): added a new table request_log

controllers/userController.js, models/userModel.js
Fixed parameter definition in controller
None
None
=> fix: request parameters in controller

CHANGELOG.md
Updated the ` CHANGELOG.md` for version 0.3
Release of version 0.3
N/A
=> feat: updated changelog for release 0.3

models/applicantModel.js
Updated the endpoint `get-completed-requests` to obtain cancelled and rejected requests
n/a
n/a
=> feat: included cancelled and rejected requests in get completed requests

test/TravelAgent/attendTravelRequest.test.js
Includes a unit test for the endpoint /attend-travel-request/:request_id on behalf of the travel agent
#375 
#323
=> test: attend travel request travel agent

test/TravelAgent/attendTravelRequest.test.js
This PR contains the tests for the endpoints /travel-agent/
#323
N/A
=> 375 sub task test travel agent endpoints

.env.example, controllers/userController.js, middleware/auth.js, middleware/decryption.js, models/userModel.js, routes/accountsPayableRoutes.js, routes/adminRoutes.js, routes/applicantRoutes.js, routes/authorizerRoutes.js, routes/travelAgentRoutes.js, routes/userRoutes.js, services/adminService.js, services/userService.js
This endpoint integrates the route protection with the JSON Web Token, as well, there was a minor change in the encryption and decryption of data. 
N/A
N/A
=> Route role protection using jwt and encryption fixes

controllers/adminController.js, database/Schema/Dummy.sql, database/config/dev_db.js, database/config/dummy_users.csv, services/adminService.js
when running pnpm dummy_db it creates a dummy users with a csv
n/a
n/a
=> 320 task create scv file for users information to be encrypted once stored in the db

controllers/userController.js, models/userModel.js, routes/userRoutes.js
This feature adds a new endpoint GET  get-request-logs  that retrieves the complete history of status changes for a specific request. The implementation required modifications to three files: userRoutes.js to add the new route with proper validation middleware, userModel.js to create the database query that joins Request_log, Request_status, and User tables to fetch the necessary information, and userController.js to handle the request, format the response with separated date and time fields, and implement proper error handling. The endpoint returns a chronological list of all status changes, including who made each change and when it occurred, providing a complete audit trail for request modifications.
https://github.com/101-Coconsulting/TC3005B.501-Backend/issues/319
=> feat: implement request logs endpoint to get the historical data of a request

database/Schema/Dummy.sql, test/Applicant/sendExpenseValidation.test.js
Test for send expense validation endpoint
None
None
=> feat: add sendExpenseValidation test

test/Admin/getUserList.test.js
This PR tests the endpoint /admin/get-user-list
#373 
N/A
=> test: get user list endpoint

test/accountsPayable/attendTravelRequest.test.js
Add Mocha/Chai integration tests for attendTravelRequest endpoint
=> test:  attendTravelRequest endpoint

test/Authorizer/getAlerts.test.js
Test for getAlerts endpoint
#374 
n/a
=> chore: added test for getAlerts

controllers/adminController.js, models/adminModel.js, routes/adminRoutes.js, services/adminService.js
> Added endpoint to update user
As per @A09271's description of closed PR #336.
This includes an administrator endpoint in change of updating a user's information, while verifying that the information given is not yet present in the database for sensible data that should remain unique, while minding the security requirements for the proper handling of the user information.
This PR was opened by me but only for `git` history fixing. The responsibility of this PR and the changes made by it and to it falls to @A09271 , so be sure to tag him in any comment that requires their attention.
_N/A_ (Could have been #161, but it's already finished.)
_N/A_ (Could have been #161, but it's already finished.)
=> 160 sub task create endpoint update useruser

test/User/login.test.js
- [] PR is from a feature branch based on `development`.
- [] PR is being made to the `development` branch.
This PR adds a testing suite for the `user/login` endpoint.  
It includes:
- Validation of required fields and input structure  
- Tests for successful login with valid credentials  
- Tests for error conditions (invalid credentials, missing fields, empty fields)  
- Status code assertions for all scenarios  
- Checks for correct error messaging and token presence
- [Sub-Task]: Test User endpoints #376
- N/A
=> Test: Test Login

test/User/logout.test.js
- [] PR is from a feature branch based on `development`.
- [] PR is being made to the `development` branch.
This PR adds a test for the `/api/user/logout` endpoint.  
It includes:
- A GET request to `/api/user/logout`
- Asserts status code 200
- Asserts the response contains `{ message: "Sesión cerrada correctamente" }`
- Matches the current controller and route implementation
- #376 
- N/A
=> Test: Test for User Logout

controllers/applicantController.js, models/applicantModel.js, routes/applicantRoutes.js, services/receiptFileService.js
- **feat: added /delete-receipt/:id to applicant**
- **feat: the /delete-receipt endpoint now also deletes the files in the mongodb repository.**
Endpoint to delete a receipt registry from both mariadb and files from mongodb
N/A
N/A
=> 428 delete receiptreceipt id

test/accountsPayable/validateReceipts.test.js
Add tests for validate-receipts endpoint - Added comprehensive test cases for the validate-receipts endpoint, including successful validation (200), handling of non-existent request IDs (200), invalid request ID format validation (400), and requests with no receipts (200). All test cases are implemented and passing successfully.
https://github.com/101-Coconsulting/TC3005B.501-Backend/issues/372
https://github.com/101-Coconsulting/TC3005B.501-Backend/issues/323
=> test: add tests for validate-receipts endpoin

test/User/getTravelRequest.test.js, test/User/getTravelRequests.test.js, test/User/getUserData.test.js, test/User/login.test.js, test/User/logout.test.js
Encompasses all tests for the user endpoints
N/A
#323
=> 376 sub task test user endpoints

test/Authorizer/authorizeTravelRequest.test.js
This PR tests the endpoint authorize travel request
#374
N/A
=> test: authorize travel request

routes/adminRoutes.js
Added route role protection to last admin endpoints recently merged.
N/A
N/A
=> Add role route protection to missing admin endpoints

models/adminModel.js, services/adminService.js
validates if any emails repeats itself inside the database when creating a user or multiple of them
n/a
n/a
=> 423 change email validation when creating a new user

controllers/fileController.js, middleware/mongoSanitize.js, package.json, routes/fileRoutes.js, services/fileStorage.js
- **refactor: changed the file system code to use a controller and have cleaner routes**
- **feat: added sanitization using mongo-sanitize. Mostly changed the params and body**
Added a middleware and changed code to use mongo-sanitize module to sanitize inputs going to the mongodb database.
NA
NA
=> MongoDB Sanitization
